# Generated by Django 5.1.6 on 2025-02-10 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='bio',
            new_name='about_me',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status_cat',
            field=models.CharField(choices=[('Для взрослого и ребёнка', 'Для взрослого и ребёнка'), ('Для взрослого', 'Для взрослого'), ('Для ребёнка', 'Для ребёнка')], max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status_edu',
            field=models.CharField(choices=[('Кандидат мединциских наук', 'Кандидат мединциских наук'), ('Доктор мединциских наук', 'Доктор мединциских наук'), ('Высшее образование', 'Высшее образование')], max_length=255),
        ),
    ]
