# Generated by Django 5.1.6 on 2025-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient_alter_doctor_status_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status_cat',
            field=models.CharField(choices=[('Для взрослого', 'Для взрослого'), ('Для взрослого и ребёнка', 'Для взрослого и ребёнка'), ('Для ребёнка', 'Для ребёнка')], max_length=255),
        ),
        migrations.DeleteModel(
            name='ConsultZapis',
        ),
    ]
