# Generated by Django 5.1.6 on 2025-02-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_status_cat_delete_consultzapis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patient'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='status_cat',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status_edu',
            field=models.CharField(choices=[('Кандидат мединциских наук', 'Кандидат мединциских наук'), ('Высшее образование', 'Высшее образование'), ('Доктор мединциских наук', 'Доктор мединциских наук')], max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='category_consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='users.categoryconsultation'),
            preserve_default=False,
        ),
    ]
