# Generated by Django 5.1.6 on 2025-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_status_edu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='category_consultation',
        ),
        migrations.AddField(
            model_name='doctor',
            name='status_cat',
            field=models.CharField(choices=[('Для взрослого и ребёнка', 'Для взрослого и ребёнка'), ('Для взрослого', 'Для взрослого'), ('Для ребёнка', 'Для ребёнка')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status_edu',
            field=models.CharField(choices=[('Кандидат мединциских наук', 'Кандидат мединциских наук'), ('Доктор мединциских наук', 'Доктор мединциских наук'), ('Высшее образование', 'Высшее образование')], max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoryConsultation',
        ),
    ]
