# Generated by Django 5.1.6 on 2025-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_doctor_category_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status_cat',
            field=models.CharField(choices=[('Для взрослого и ребёнка', 'Для взрослого и ребёнка'), ('Для ребёнка', 'Для ребёнка'), ('Для взрослого', 'Для взрослого')], max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status_edu',
            field=models.CharField(choices=[('Кандидат мединциских наук', 'Кандидат мединциских наук'), ('Высшее образование', 'Высшее образование'), ('Доктор мединциских наук', 'Доктор мединциских наук')], max_length=255),
        ),
    ]
