# Generated by Django 5.1.6 on 2025-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_doctor_status_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status_edu',
            field=models.CharField(choices=[('Высшее образование', 'Высшее образование'), ('Кандидат мединциских наук', 'Кандидат мединциских наук'), ('Доктор мединциских наук', 'Доктор мединциских наук')], max_length=255),
        ),
    ]
