# Generated by Django 5.1.6 on 2025-02-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
        ('users', '0004_alter_doctor_status_cat_delete_consultzapis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='div_tile1',
            new_name='div_title1',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='div_tile2',
            new_name='div_title2',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='div_tile3',
            new_name='div_title3',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='div_tile4',
            new_name='div_title4',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='title',
            new_name='title_blue',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='older_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='older_tupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_white',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsultZapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_con', models.DateTimeField()),
                ('end_con', models.DateTimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedlinkPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='medicine_app.mainpage')),
            ],
        ),
    ]
