# Generated by Django 5.1.6 on 2025-02-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultzapis',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='consultzapis',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='mainpageicons',
            name='mainpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons_main', to='medicine_app.mainpage'),
        ),
        migrations.AddField(
            model_name='medlinkpersonal',
            name='main_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='medicine_app.mainpage'),
        ),
        migrations.AddField(
            model_name='questionsmp',
            name='mainpage_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_main', to='medicine_app.mainpage'),
        ),
    ]
