# Generated by Django 5.1.6 on 2025-02-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_rename_div_tile1_mainpage_div_title1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='older_tupe',
            new_name='older_type',
        ),
    ]
